export const mockClients = [
  {
    id: 1,
    name: 'Иван Петров',
    phone: '+34 612 345 678',
    email: 'ivan.petrov@email.com',
    avatar: '/images/clients/client-01.jpg',
    memberSince: 'Март 2023',
    totalBookings: 12,
    totalSpent: 3840,
    status: 'active',
  },
  {
    id: 2,
    name: 'Мария Иванова',
    phone: '+34 633 456 789',
    email: 'maria.ivanova@email.com',
    avatar: '/images/clients/client-02.jpg',
    memberSince: 'Июнь 2025',
    totalBookings: 7,
    totalSpent: 2210,
    status: 'active',
  },
  {
    id: 3,
    name: 'Алексей Смирнов',
    phone: '+34 634 567 890',
    email: 'alexey.smirnov@email.com',
    avatar: '/images/clients/client-03.jpg',
    memberSince: 'Январь 2024',
    totalBookings: 3,
    totalSpent: 660,
    status: 'active',
  },
  {
    id: 4,
    name: 'Елена Кузнецова',
    phone: '+34 645 678 901',
    email: 'elena.kuznetsova@email.com',
    avatar: '/images/clients/client-04.jpg',
    memberSince: 'Сентябрь 2022',
    totalBookings: 21,
    totalSpent: 6120,
    status: 'active',
  },
  {
    id: 5,
    name: 'Дмитрий Волков',
    phone: '+34 656 789 012',
    email: 'dmitry.volkov@email.com',
    avatar: '/images/clients/client-05.jpg',
    memberSince: 'Апрель 2024',
    totalBookings: 1,
    totalSpent: 0,
    status: 'blocked',
  },
  {
    id: 6,
    name: 'Ольга Соколова',
    phone: '+34 667 890 123',
    email: 'olga.sokolova@email.com',
    avatar: '/images/clients/client-06.jpg',
    memberSince: 'Декабрь 2023',
    totalBookings: 9,
    totalSpent: 2840,
    status: 'active',
  },
  {
    id: 7,
    name: 'Андрей Никитин',
    phone: '+34 678 901 234',
    email: 'andrey.nikitin@email.com',
    avatar: '/images/clients/client-07.jpg',
    memberSince: 'Май 2023',
    totalBookings: 5,
    totalSpent: 1120,
    status: 'active',
  },
  {
    id: 8,
    name: 'Виктория Сидорова',
    phone: '+34 689 012 345',
    email: 'victoria.sidorova@email.com',
    avatar: '/images/clients/client-08.jpg',
    memberSince: 'Июль 2024',
    totalBookings: 4,
    totalSpent: 1480,
    status: 'active',
  },
  {
    id: 9,
    name: 'Ольга Ковалёва',
    phone: '+34 622 334 455',
    email: 'olga.kovaleva@email.com',
    avatar: '/images/clients/client-09.jpg',
    memberSince: 'Февраль 2023',
    totalBookings: 14,
    totalSpent: 4390,
    status: 'active',
  },
  {
    id: 10,
    name: 'Наталья Морозова',
    phone: '+34 611 223 344',
    email: 'natalia.morozova@email.com',
    avatar: '/images/clients/client-10.jpg',
    memberSince: 'Октябрь 2023',
    totalBookings: 6,
    totalSpent: 1950,
    status: 'active',
  },
];
