export const mockCars = [
  {
    id: 1,
    brand: 'Tesla',
    model: 'Model 3 LR',
    plate: 'AA1234BC',
    imagePreview: '/images/cars/audi.jpg',
    type: 'Электро',
    status: 'rented',
    driver: { name: 'Иван Петров', phone: '+34 612 345 678', email: 'ivan.petrov@email.com' },
    rentStart: '23 мая 2024, 10:00',
    rentEnd: '25 мая 2024, 18:00',
    mileageTotal: 84250,
    mileageToday: 152,
    fuelLevel: 78,
    location: {
      city: 'Madrid',
      country: 'Испания',
      address: 'Calle de Alcalá, 123, 28009 Madrid, España',
    },
    speed: 72,
    ignition: true,
    voltage: 12.6,
    temperature: 23,
    attentionNote: null,
    notifications: [
      { id: 1, title: 'Превышение скорости', detail: '128 км/ч на A-3', time: '23 мая, 12:51' },
    ],
  },
  {
    id: 2,
    brand: 'BMW',
    model: 'X5 xDrive40i',
    plate: 'BB5678DE',
    imagePreview: '/images/cars/citroen.jpg',
    type: 'Бензин',
    status: 'available',
    driver: null,
    rentStart: null,
    rentEnd: null,
    mileageTotal: 67890,
    mileageToday: 0,
    fuelLevel: 61,
    location: {
      city: 'Barcelona',
      country: 'Испания',
      address: 'Carrer de Balmes, 45, 08007 Barcelona, España',
    },
    speed: null,
    ignition: false,
    voltage: 12.4,
    temperature: 21,
    attentionNote: null,
    notifications: [],
  },
  {
    id: 3,
    brand: 'Audi',
    model: 'A4 Avant',
    plate: 'CC9012FG',
    imagePreview: '/images/cars/mers.jpg',
    type: 'Дизель',
    status: 'rented',
    driver: { name: 'Мария Иванова', phone: '+34 655 112 233', email: 'maria.ivanova@email.com' },
    rentStart: '22 мая 2024, 09:00',
    rentEnd: '24 мая 2024, 14:00',
    mileageTotal: 45230,
    mileageToday: 210,
    fuelLevel: 45,
    location: {
      city: 'Valencia',
      country: 'Испания',
      address: 'Av. del Puerto, 12, 46021 Valencia, España',
    },
    speed: 85,
    ignition: true,
    voltage: 12.5,
    temperature: 24,
    attentionNote: null,
    notifications: [],
  },
  {
    id: 4,
    brand: 'Mercedes',
    model: 'C200',
    plate: 'DD3456HI',
    imagePreview: '/images/cars/audi.jpg',
    type: 'Бензин',
    status: 'maintenance',
    driver: null,
    rentStart: null,
    rentEnd: null,
    mileageTotal: 92100,
    mileageToday: 0,
    fuelLevel: null,
    location: { city: 'Madrid', country: 'Испания', address: 'Сервис центр, Madrid' },
    speed: null,
    ignition: false,
    voltage: 12.1,
    temperature: 19,
    attentionNote: 'На плановом ТО',
    notifications: [],
  },
  {
    id: 5,
    brand: 'Volkswagen',
    model: 'Golf',
    plate: 'EE7890JK',
    imagePreview: '/images/cars/audi.jpg',
    type: 'Бензин',
    status: 'available',
    driver: null,
    rentStart: null,
    rentEnd: null,
    mileageTotal: 38765,
    mileageToday: 0,
    fuelLevel: 55,
    location: {
      city: 'Sevilla',
      country: 'Испания',
      address: 'Av. de la Constitución, 8, 41001 Sevilla, España',
    },
    speed: null,
    ignition: false,
    voltage: 12.3,
    temperature: 22,
    attentionNote: null,
    notifications: [],
  },
  {
    id: 6,
    brand: 'Toyota',
    model: 'RAV4 Hybrid',
    plate: 'FF1122LM',
    imagePreview: '/images/cars/audi.jpg',
    type: 'Гибрид',
    status: 'rented',
    driver: {
      name: 'Алексей Смирнов',
      phone: '+34 677 889 900',
      email: 'alexey.smirnov@email.com',
    },
    rentStart: '24 мая 2024, 10:00',
    rentEnd: '26 мая 2024, 10:00',
    mileageTotal: 73450,
    mileageToday: 98,
    fuelLevel: 67,
    location: {
      city: 'Zaragoza',
      country: 'Испания',
      address: 'Paseo Independencia, 20, 50004 Zaragoza, España',
    },
    speed: 64,
    ignition: true,
    voltage: 12.6,
    temperature: 25,
    attentionNote: null,
    notifications: [],
  },
  {
    id: 7,
    brand: 'Skoda',
    model: 'Octavia',
    plate: 'GG3344NP',
    imagePreview: '/images/cars/audi.jpg',
    type: 'Дизель',
    status: 'attention',
    driver: null,
    rentStart: null,
    rentEnd: null,
    mileageTotal: 56300,
    mileageToday: 0,
    fuelLevel: 33,
    location: { city: 'Bilbao', country: 'Испания', address: 'Gran Vía, 15, 48001 Bilbao, España' },
    speed: null,
    ignition: false,
    voltage: 11.9,
    temperature: 18,
    attentionNote: 'Техосмотр просрочен',
    notifications: [
      { id: 1, title: 'Техосмотр просрочен', detail: 'Истёк 10 мая 2024', time: '10 мая, 09:00' },
    ],
  },
  {
    id: 8,
    brand: 'Kia',
    model: 'Sportage',
    plate: 'HH5566QR',
    imagePreview: '/images/cars/audi.jpg',
    type: 'Бензин',
    status: 'available',
    driver: null,
    rentStart: null,
    rentEnd: null,
    mileageTotal: 29150,
    mileageToday: 0,
    fuelLevel: 72,
    location: {
      city: 'Malaga',
      country: 'Испания',
      address: 'Calle Larios, 5, 29005 Malaga, España',
    },
    speed: null,
    ignition: false,
    voltage: 12.5,
    temperature: 26,
    attentionNote: null,
    notifications: [],
  },
  {
    id: 9,
    brand: 'Hyundai',
    model: 'Tucson',
    plate: 'II7788RS',
    imagePreview: '/images/cars/audi.jpg',
    type: 'Бензин',
    status: 'rented',
    driver: { name: 'Ольга Ковалёва', phone: '+34 622 334 455', email: 'olga.kovaleva@email.com' },
    rentStart: '23 мая 2024, 08:00',
    rentEnd: '26 мая 2024, 12:00',
    mileageTotal: 33760,
    mileageToday: 92,
    fuelLevel: 40,
    location: {
      city: 'Alicante',
      country: 'Испания',
      address: 'Explanada de España, 2, 03002 Alicante, España',
    },
    speed: 60,
    ignition: true,
    voltage: 12.4,
    temperature: 24,
    attentionNote: null,
    notifications: [],
  },
  {
    id: 10,
    brand: 'Renault',
    model: 'Duster',
    plate: 'JJ9900TU',
    imagePreview: '/images/cars/audi.jpg',
    type: 'Бензин',
    status: 'available',
    driver: null,
    rentStart: null,
    rentEnd: null,
    mileageTotal: 41005,
    mileageToday: 0,
    fuelLevel: 65,
    location: {
      city: 'Murcia',
      country: 'Испания',
      address: 'Gran Vía Escultor Salzillo, 1, 30004 Murcia, España',
    },
    speed: null,
    ignition: false,
    voltage: 12.3,
    temperature: 23,
    attentionNote: null,
    notifications: [],
  },
  {
    id: 11,
    brand: 'Renault',
    model: 'Duster',
    plate: 'JJ9900TU',
    imagePreview: '/images/cars/audi.jpg',
    type: 'Бензин',
    status: 'available',
    driver: null,
    rentStart: null,
    rentEnd: null,
    mileageTotal: 41005,
    mileageToday: 0,
    fuelLevel: 65,
    location: {
      city: 'Murcia',
      country: 'Испания',
      address: 'Gran Vía Escultor Salzillo, 1, 30004 Murcia, España',
    },
    speed: null,
    ignition: false,
    voltage: 12.3,
    temperature: 23,
    attentionNote: null,
    notifications: [],
  },
  {
    id: 12,
    brand: 'Renault',
    model: 'Duster',
    plate: 'JJ9900TU',
    imagePreview: '/images/cars/audi.jpg',
    type: 'Бензин',
    status: 'available',
    driver: null,
    rentStart: null,
    rentEnd: null,
    mileageTotal: 41005,
    mileageToday: 0,
    fuelLevel: 65,
    location: {
      city: 'Murcia',
      country: 'Испания',
      address: 'Gran Vía Escultor Salzillo, 1, 30004 Murcia, España',
    },
    speed: null,
    ignition: false,
    voltage: 12.3,
    temperature: 23,
    attentionNote: null,
    notifications: [],
  },
  {
    id: 13,
    brand: 'Renault',
    model: 'Duster',
    plate: 'JJ9900TU',
    imagePreview: '/images/cars/audi.jpg',
    type: 'Бензин',
    status: 'available',
    driver: null,
    rentStart: null,
    rentEnd: null,
    mileageTotal: 41005,
    mileageToday: 0,
    fuelLevel: 65,
    location: {
      city: 'Murcia',
      country: 'Испания',
      address: 'Gran Vía Escultor Salzillo, 1, 30004 Murcia, España',
    },
    speed: null,
    ignition: false,
    voltage: 12.3,
    temperature: 23,
    attentionNote: null,
    notifications: [],
  },
  {
    id: 14,
    brand: 'Renault',
    model: 'Duster',
    plate: 'JJ9900TU',
    imagePreview: '/images/cars/audi.jpg',
    type: 'Бензин',
    status: 'available',
    driver: null,
    rentStart: null,
    rentEnd: null,
    mileageTotal: 41005,
    mileageToday: 0,
    fuelLevel: 65,
    location: {
      city: 'Murcia',
      country: 'Испания',
      address: 'Gran Vía Escultor Salzillo, 1, 30004 Murcia, España',
    },
    speed: null,
    ignition: false,
    voltage: 12.3,
    temperature: 23,
    attentionNote: null,
    notifications: [],
  },
  {
    id: 15,
    brand: 'Renault',
    model: 'Duster',
    plate: 'JJ9900TU',
    imagePreview: '/images/cars/audi.jpg',
    type: 'Бензин',
    status: 'available',
    driver: null,
    rentStart: null,
    rentEnd: null,
    mileageTotal: 41005,
    mileageToday: 0,
    fuelLevel: 65,
    location: {
      city: 'Murcia',
      country: 'Испания',
      address: 'Gran Vía Escultor Salzillo, 1, 30004 Murcia, España',
    },
    speed: null,
    ignition: false,
    voltage: 12.3,
    temperature: 23,
    attentionNote: null,
    notifications: [],
  },
];
